# ==== pytest ====
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "configs.settings.local"
minversion = "7.4"
addopts = "--ds=configs.settings.test --reuse-db"
python_files = [
    "tests.py",
    "test_*.py",
]
filterwarnings = ["ignore::DeprecationWarning", "ignore::django.utils.deprecation.RemovedInDjango51Warning"]

# ==== ruff ====
[tool.ruff]
select = ["ALL"]
ignore = [
    "A002", "A003", "ARG001", "ARG002", "C901", "COM812", "D100",
    "D101", "D102", "D103", "D105", "D106", "D200", "D202", "D205", "D212", "D415", "DJ001",
    "EM101", "EM102", "ERA001", "FBT001", "FBT002", "G004", "I001", "INP001",
    "PLR0912", "PLR0913", "PLR2004", "PT009", "PTH103", "PTH120", "PTH122", "PTH123",
    "RUF001", "RUF002", "RUF003", "RUF012", "S308", "SLF001", "TID252", "TRY003", "TRY401",

    "ANN", "FIX",  "TD",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*/migrations",
    "__init__.py",
    "scripts",
    "manage.py",
    "configs/settings/*.py"]

# Same as Black.
line-length = 120

# Assume Python 3.11
target-version = "py311"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

# ==== black ====
[tool.black]
line-length = 120
target-version = ['py311']
force-exclude = "venv|migrations|data|configs/settings|requirements.txt|requirements-dev.txt"


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
default_section = "THIRDPARTY"
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = ["confessions_website",
    "configs",
    "config",
]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]

# ==== pyright ====
[tool.pyright]
exclude = [
    ".mypy_cache",
    "**/__pycache__",
    "dev",
    "venv",
    "migrations/env.py",
]


# ==== bandit ====
[tool.bandit]
exclude_dirs = ["dev", "venv"]
skips = ["B703", "B308"]


# ==== pylint ====
[tool.pylint.main]
jobs = 0
ignore-paths = [
    "venv",
    "migrations",
    "docker/superset/pythonpath/superset_config.py",
]
# Разрешение f-string в логировании
disable = ["logging-fstring-interpolation"]

[tool.pylint.format]
max-line-length = 120


# ==== misc ====
venv = "venv"
pythonVersion = "3.11"
