version: "3.9"


services:
  redis:
    image: redis:7.2-alpine
    hostname: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    hostname: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./docker/clickhouse:/docker-entrypoint-initdb.d
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - .env

  postgres:
    image: postgres:16.1-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    restart: always
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - clickhouse
      - postgres

volumes:
  redis-data:
  clickhouse-data:
  postgres-data:
