services:
  redis:
    image: redis:7.2-alpine
    command: --port ${REDIS_PORT:-6379}
    hostname: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    env_file:
      - .env

  postgres:
    image: postgres:16.1-alpine
    hostname: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${PGPORT:-5432}:${PGPORT:-5432}"

  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python", "main.py" ]
    restart: always
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - clickhouse
      - postgres

  migrate:
    extends:
      service: bot
    command: [ "alembic", "upgrade", "head" ]
    restart: no

volumes:
  redis-data:
  postgres-data:
  clickhouse-data:
